### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'TF'

### ISSUE THREAD

**Issue by Zifeng1995** [aertslab/SCENICprotocol#15]
I tried the tutorial named pySCENIC protocol: PBMC10k using the dataset from 10X Genomics.
However, I got the error as followed. I checked the adj.csv, there seemed nothing wrong with it. Can anyone help me?
```
!pyscenic ctx /cluster/home/zfli/RProject/Lymphoma/SCENIC/pbmc10k/adjacencies.csv \
    /cluster/home/zfli/Rcistarget/hg38/hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather /cluster/home/zfli/Rcistarget/hg38/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather \
    --annotations_fname /cluster/home/zfli/Rcistarget/motifs-v9-nr.hgnc-m0.001-o0.0.tbl \
    --expression_mtx_fname /cluster/home/zfli/RProject/Lymphoma/SCENIC/pbmc10k/pbmc10k_filtered_scenic.loom \
    --output /cluster/home/zfli/RProject/Lymphoma/SCENIC/pbmc10k/reg.csv \
    --mask_dropouts \
    --num_workers 4
```

```
2020-06-16 21:02:43,453 - pyscenic.cli.pyscenic - INFO - Creating modules.

2020-06-16 21:02:46,486 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-06-16 21:02:50,491 - pyscenic.utils - INFO - Calculating Pearson correlations.

2020-06-16 21:02:50,491 - pyscenic.utils - WARNING - Note on correlation calculation: the default behaviour for calculating the correlations has changed after pySCENIC verion 0.9.16. Previously, the default was to calculate the correlation between a TF and target gene using only cells with non-zero expression values (mask_dropouts=True). The current default is now to use all cells to match the behavior of the R verision of SCENIC. The original settings can be retained by setting 'rho_mask_dropouts=True' in the modules_from_adjacencies function, or '--mask_dropouts' from the CLI.
	Dropout masking is currently set to [True].
Traceback (most recent call last):
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 421, in main
    args.func(args)
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 140, in prune_targets_command
    modules = adjacencies2modules(args)
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 109, in adjacencies2modules
    keep_only_activating=(args.all_modules != "yes"))
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/utils.py", line 268, in modules_from_adjacencies
    rho_threshold=rho_threshold, mask_dropouts=rho_mask_dropouts)
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/utils.py", line 129, in add_correlation
    col_idx_pairs = _create_idx_pairs(adjacencies, ex_mtx)
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pyscenic/utils.py", line 70, in _create_idx_pairs
    genes = set(adjacencies.TF).union(set(adjacencies.target))
  File "/cluster/home/zfli/anaconda2/envs/scanpy_env/lib/python3.6/site-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'TF'
```
![image](https://user-images.githubusercontent.com/53402047/84779986-a22fcf00-b017-11ea-9f4d-d84698da538a.png)

**Comment by cflerin** [comment]
Hi @Zifeng1995 , 

Can you tell me the pandas version you're using? (`pd.__version__`).

Also, can you show the output of your column names from `adjacencies.columns`?

**Comment by Zifeng1995** [comment]
> 嗨@ Zifeng1995，
> 
> 您能告诉我您使用的熊猫版本吗？（`pd.__version__`）。
> 
> 另外，您可以显示来自的列名的输出`adjacencies.columns`吗？

pandas version 0.23.4
![image](https://user-images.githubusercontent.com/53402047/84785758-719f6380-b01e-11ea-96f0-8515cbc3c85a.png)

**Comment by cflerin** [comment]
Ok, it's really hard to tell from the formatting in your screenshot, but is there whitespace in your column names? If you could copy/paste the output into a codeblock, it will make it a lot easier to read:

\```
`Index(['TF', 'target', 'importance'], dtype='object')`
\```

**Comment by Zifeng1995** [comment]
> Ok, it's really hard to tell from the formatting in your screenshot, but is there whitespace in your column names? If you could copy/paste the output into a codeblock, it will make it a lot easier to read:
> 
> ```
> `Index(['TF', 'target', 'importance'], dtype='object')`
> ```

yes, there is whitespace in my column names.
`Index(['TF', 'target', 'importance'], dtype='object')`

**Comment by cflerin** [comment]
Ok, so it actually looks like there are no spaces in the column names. So I'm not quite sure what's happening here. Is the problem still happening with the data you're running in #14 ?
