### ISSUE TITLE
Singularity containers do not fully isolate the user home

### ISSUE THREAD

**Issue by cflerin** [aertslab/SCENICprotocol#2]
In cases where there is already a local Scanpy install in the user home directory:
`~/.local/lib/python3.7/site-packages/scanpy`, Singularity tries to use this install before the container version, resulting in:
```
Error executing process > 'filter'

Caused by:
  Process `filter` terminated with an error exit status (1)

Command executed:

  filtering-basic.py         --loom_input expr_mat.loom         --loom_filtered filtered.loom         --thr_min_genes 200         --thr_min_cells 3         --thr_n_genes 5000         --thr_pct_mito 0.25

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/path/to/SCENICprotocol/bin/filtering-basic.py", line 5, in <module>
      import scanpy as sc
    File "/user/leuven/325/vsc32528/.local/lib/python3.7/site-packages/scanpy/__init__.py", line 3, in <module>
      from ._utils import pkg_version, check_versions, annotate_doc_types
    File "/user/leuven/325/vsc32528/.local/lib/python3.7/site-packages/scanpy/_utils.py", line 17, in <module>
      from packaging import version
  ModuleNotFoundError: No module named 'packaging'

Work dir:
  /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/testruns/scenic-protocol/contain_test/work/ce/731fb8cee41978b6352a534825a95d

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

This can be fixed by using the `contain` option:
`singularity run --contain aertslab/pyscenic:0.9.18 [...]`
or, in Nextflow:
`singularity.runOptions = '--contain'`

**Comment by cflerin** [comment]
It seems that this doesn't solve the problem entirely. Using `--contain` means that the project bin folder now can't be mounted:
```
Error executing process > 'filter'

Caused by:
  Process `filter` terminated with an error exit status (255)

Command executed:

  filtering-basic.py         --loom_input expr_mat.loom         --loom_filtered filtered.loom         --thr_min_genes 200         --thr_min_cells 3         --thr_n_genes 5000         --thr_pct_mito 0.25

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   container creation failed: mount ->/user/leuven/325/vsc32528/.nextflow/assets/aertslab/SCENICprotocol/bin error: can't remount /user/leuven/325/vsc32528/.nextflow/assets/aertslab/SCENICprotoco
l/bin: no such file or directory

Work dir:
  /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/testruns/scenic-protocol/contain_test/work/7f/49bad2650dd0567cbdfb0b5056c6e8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

However, replacing `--contain` with `--no-home` does appear to work. This now requires setting an environmental variable for numba (`NUMBA_CACHE_DIR`).
