### ISSUE TITLE
AttributeError: module 'numba' has no attribute 'jitclass'

### ISSUE THREAD

**Issue by Lee0498** [aertslab/SCENICprotocol#34]
I tried the tutorial to install the pySCENIC followed by the file named installation.md. 
However,when I tried the basic test for the whole environment, I got the error as followed. There is no attribute 'jitclass' for 'numba' . Can anyone help me?
``` {kernal}
pyscenic -h

/Users/lichengyu/opt/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}


Traceback (most recent call last):
  File "/Users/lichengyu/opt/anaconda3/envs/scenic_protocol/bin/pyscenic", line 5, in <module>
    from pyscenic.cli.pyscenic import main
  File "/Users/lichengyu/opt/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/pyscenic/cli/pyscenic.py", line 19, in <module>
    from pyscenic.utils import modules_from_adjacencies, add_correlation
  File "/Users/lichengyu/opt/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/pyscenic/utils.py", line 6, in <module>
    from .math import masked_rho4pairs
  File "/Users/lichengyu/opt/anaconda3/envs/scenic_protocol/lib/python3.6/site-packages/pyscenic/math.py", line 5, in <module>
    from numba import *
AttributeError: module 'numba' has no attribute 'jitclass'
```

Here are all my installed packages in the environment.

```{kernal}# Name                    Version                   Build  Channel
anndata                   0.7.5                    pypi_0    pypi
arboreto                  0.1.5                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
boltons                   20.2.1                   pypi_0    pypi
ca-certificates           2020.12.5            h033912b_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cairo                     1.16.0            h4ec454a_1007    conda-forge
certifi                   2020.12.5        py36h79c6626_1    conda-forge
cffi                      1.14.4           py36hfe0777f_1    conda-forge
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py36haf1e3a3_0    anaconda
dask                      1.0.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
distributed               1.28.1                   pypi_0    pypi
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
frozendict                1.2                      pypi_0    pypi
get-version               2.1                      pypi_0    pypi
gettext                   0.19.8.1          h7937167_1005    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
h5py                      3.1.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
icu                       68.1                 h74dc148_0    conda-forge
importlib-metadata        3.4.0                    pypi_0    pypi
interlap                  0.2.7                    pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py36h615c93b_1    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
legacy-api-wrap           1.2                      pypi_0    pypi
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_17    conda-forge
libgfortran5              9.3.0               h6c81a4c_17    conda-forge
libglib                   2.66.4               h7424822_1    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
llvmlite                  0.35.0                   pypi_0    pypi
loompy                    3.0.6                    pypi_0    pypi
louvain                   0.7.0            py36h59ef8ac_1    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
matplotlib                3.3.3            py36h79c6626_0    conda-forge
matplotlib-base           3.3.3            py36hbcb57cb_0    conda-forge
msgpack                   1.0.2                    pypi_0    pypi
multicore-tsne            0.1_d4ff4aab     py36h3e44d54_0    conda-forge
multiprocessing-on-dill   3.5.0a4                  pypi_0    pypi
natsort                   7.1.0                    pypi_0    pypi
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.5                      pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numexpr                   2.7.2                    pypi_0    pypi
numpy                     1.19.5           py36h08dc641_1    conda-forge
numpy-groupies            0.9.13                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
packaging                 20.8                     pypi_0    pypi
pandas                    0.25.3                   pypi_0    pypi
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pillow                    8.1.0            py36hc04f27d_1    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
psutil                    5.8.0                    pypi_0    pypi
pyarrow                   0.16.0                   pypi_0    pypi
pycairo                   1.20.0           py36h7d97dce_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyscenic                  0.10.4                   pypi_0    pypi
python                    3.6.12          h6c3b2c9_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-igraph             0.8.3            py36he18b813_3    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.0                  h0678c8f_2    conda-forge
scanpy                    1.6.1                    pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.5.3            py36h04de62b_0    conda-forge
seaborn                   0.11.1               h694c41f_0    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py36h79c6626_3    conda-forge
setuptools-scm            5.0.1                    pypi_0    pypi
sinfo                     0.3.1                    pypi_0    pypi
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sortedcontainers          2.3.0                    pypi_0    pypi
sqlite                    3.34.0               h17101e1_0    conda-forge
statsmodels               0.12.1           py36h809c706_2    conda-forge
stdlib-list               0.8.0                    pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
texttable                 1.6.3              pyh9f0ad1d_0    conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               h0419947_1    conda-forge
toolz                     0.11.1                     py_0    anaconda
tornado                   6.1              py36h20b66c6_1    conda-forge
tqdm                      4.56.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
umap-learn                0.4.6                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zict                      2.0.0                    pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge```

**Comment by cflerin** [comment]
Hi @Lee0498 ,

I recommend downgrading numba to an earlier verison, see here: aertslab/pySCENIC/issues/245
