### ISSUE TITLE
Dask workers failing when working with large dataset on HPC

### ISSUE THREAD

**Issue by FloWuenne** [aertslab/SCENICprotocol#4]
Hi there, 

thanks for the great package. It makes it very easy to run the complete SCENIC workflow.

I have SCENICprotocol setup on an HPC running SLURM, singularity (aertslab-pySCENIC-0.9.18.img) and submitting the small test dataset works without a problem. When I run a small subset of my data (5% of complete dataset, ~3k cells, converted to loom from a Seurat object) it also works without an issue using 10 threads and 4G per thread.

When I try to run my entire dataset consisting of 62k cells, the pipeline fails during GRNinference. 

I don't know where the issue is coming from, as the loom objects for the subset and the full dataset are similar except for cell number. Could this be related to RAM available on each worker?

Any help with this would be much appreciated!

Thanks, here are the command and errors:

**This is the command executed in the pipeline:** 

executor >  local (3)
[89/7e3133] process > filter          [100%] 1 of 1 ✔
[16/745f91] process > preprocess      [100%] 1 of 1, failed: 1
[-        ] process > pca             -
[-        ] process > visualize       -
[-        ] process > cluster         -
[b2/fbba24] process > GRNinference    [100%] 1 of 1, failed: 1 ✘
[-        ] process > cisTarget       -
[-        ] process > AUCell          -
[-        ] process > visualizeAUC    -
[-        ] process > integrateOutput -
WARN: Killing pending tasks (1)
Error executing process > 'GRNinference'

pyscenic grn         --num_workers 11         -o adj.tsv         --method grnboost2         --cell_id_attribute CellID         --gene_attribute Gene         filtered.loom         Mouse_TFs.txt

**And this is the error message:**

Command exit status:
  1

Command output:
  (empty)

Command error:
  tornado.application - ERROR - Multiple exceptions in yield list
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
      result_list.append(f.result())
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 268, in _start_worker
      raise gen.TimeoutError("Worker failed to start")
  tornado.util.TimeoutError: Worker failed to start
  Traceback (most recent call last):
    File "/usr/local/bin/pyscenic", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 408, in main
      args.func(args)
    File "/usr/local/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 64, in find_adjacencies_command
      client, shutdown_callback = _prepare_client(args.client_or_address, num_workers=args.num_workers)
    File "/usr/local/lib/python3.7/site-packages/pyscenic/prune.py", line 63, in _prepare_client
      threads_per_worker=1)
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 177, in __init__
      self.start(ip=ip, n_workers=n_workers)
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 214, in start
      self.sync(self._start, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 207, in sync
      return sync(self.loop, func, *args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 321, in sync
      six.reraise(*error[0])
    File "/usr/local/lib/python3.7/site-packages/six.py", line 693, in reraise
      raise value
    File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 306, in f
      result[0] = yield future
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
      value = future.result()
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
      yielded = self.gen.throw(*exc_info)  # type: ignore
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 239, in _start
      yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
      value = future.result()
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
      result_list.append(f.result())
    File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.7/site-packages/distributed/deploy/local.py", line 268, in _start_worker
      raise gen.TimeoutError("Worker failed to start")
  tornado.util.TimeoutError: Worker failed to start
  distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-6, started daemon)>
  distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-7, started daemon)>
  distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-8, started daemon)>
  distributed.nanny - WARNING - Worker process 203921 was killed by unknown signal
  distributed.nanny - WARNING - Worker process 203925 was killed by signal 15

**Comment by cflerin** [comment]
Hi,

Since you got the pipeline working with the test data and your own small subset, I would guess that this is a memory issue. The error from Tornado/Dask isn't very descriptive but I've seen something like this before when the processes were being killed by the system for some external reason (such as being out of memory). With 65k cells, Grnboost2 can use quite a lot of memory unfortunately (this is also dependent on the number of genes you have). If you can increase the memory assigned per process (to maybe 6-8 Gb) it could help.  

With only 10 processes, I would expect this to take a long while to run. We're working on some fixes to reduce memory usage in a future update, but for now I would guess that this would take maybe 48 hours if you have 15k or so genes. I would also suggest that you check to make sure you're happy with the cell/gene filters applied in the first step since it will take so long for the grn step.

**Comment by cflerin** [comment]
Hi Florian,

Can I suggest that you try a new option we're testing? It may be more stable when running the GRN step. You would first need to check out the branch with nextflow:
```
nextflow pull aertslab/SCENICprotocol -r mp_fix
```

Then you could run the pipeline as usual (`-resume` _may_ save you some time if you've already completed the pre-processing). Adding the `--multiprocessing` option when running should now allow GRNBoost2 to run in multiprocessing mode. For the example dataset, this would be:
```
nextflow run aertslab/SCENICprotocol -profile singularity --loom_input expr_mat.loom \
  --loom_output pyscenic_integrated-output.loom --TFs allTFs_hg38.txt \
  --motifs motifs.tbl --db *feather --threads 6 --multiprocessing -r mp_fix
```

Let me know if this helps with your current issues.

**Comment by FloWuenne** [comment]
Thanks @cflerin,

I just tried out the multiprocessing implementation and ran into the following error. I did run this in an interactive session on our HPC with 1 thread and 24G available... (just to get the node quickly and be able to test on the fly). From a quick search it seem this could be related to pickle dump?! 

executor >  local (3)
[98/70e068] process > filter          [100%] 1 of 1 ✔
[35/c21403] process > preprocess      [100%] 1 of 1, failed: 1
[-        ] process > pca             -
[-        ] process > visualize       -
[-        ] process > cluster         -
[ba/3f25f0] process > GRNinference    [100%] 1 of 1, failed: 1 ✘
[-        ] process > cisTarget       -
[-        ] process > AUCell          -
[-        ] process > visualizeAUC    -
[-        ] process > integrateOutput -
WARN: Killing pending tasks (1)
Error executing process > 'GRNinference'

Caused by:
  Process `GRNinference` terminated with an error exit status (1)

Command executed:

  pyscenic grn         --num_workers 1         -o adj.tsv         --method grnboost2         --cell_id_attribute CellID         --gene_attribute Gene         --client_or_address multiprocessing         filtered.loom         Mouse_TFs.txt

Command exit status:
  1

Command output:
  parsing input
  Running multiprocessing with 1 processes
  finished

Command error:
  
  2020-02-04 15:17:15,123 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.
  
  2020-02-04 15:17:33,199 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
  Traceback (most recent call last):
    File "/opt/venv/bin/pyscenic", line 11, in <module>
      load_entry_point('pyscenic==0.9.19+15.ge6ddaeb.dirty', 'console_scripts', 'pyscenic')()
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 424, in main
      args.func(args)
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 78, in find_adjacencies_command
      network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, multiprocessing_workers=args.num_workers, seed=args.seed)
    File "/opt/venv/lib/python3.7/site-packages/arboreto/algo.py", line 47, in grnboost2
      early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
    File "/opt/venv/lib/python3.7/site-packages/arboreto/algo.py", line 163, in diy
      seed=seed)
    File "/opt/venv/lib/python3.7/site-packages/arboreto/core.py", line 532, in run_arboreto_mp
      repeat(seed)
    File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
      return self._map_async(func, iterable, starmapstar, chunksize).get()
    File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
      raise self._value
    File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
      put(task)
    File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 206, in send
      self._send_bytes(_ForkingPickler.dumps(obj))
    File "/usr/local/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
      cls(buf, protocol).dump(obj)
  OverflowError: cannot serialize a bytes object larger than 4 GiB

**Comment by cflerin** [comment]
Hi @FloWuenne ,

Thanks for testing. It worked for me earlier (with a small dataset), but I just tried it with a larger input matrix and get the same error. Indeed, it seems to be an issue with pickle. I'll look into whether there's a good solution.

Chris

**Comment by FloWuenne** [comment]
Thanks @cflerin! Would be really cool to make this work on larger matrices as well :+1: !

**Comment by cflerin** [comment]
Hi @FloWuenne ,

Could you try out another test version? You would need to update to a different branch:
```
nextflow pull aertslab/SCENICprotocol -r mp_sparse_fixes
```
then you can run nextflow similarly to the above:
```
nextflow run aertslab/SCENICprotocol -profile singularity --loom_input expr_mat.loom \
  --loom_output pyscenic_integrated-output.loom --TFs allTFs_hg38.txt \
  --motifs motifs.tbl --db *feather --threads 15 -r mp_sparse_fixes
```
Optionally, you could also pass the `--sparse` parameter, which will load the expression data as a sparse matrix, and reduce memory usage a bit. It's worked for me in a test with a few hundred thousand cells, so I hope it doesn't crash for you this time.

**Comment by FloWuenne** [comment]
Hi @cflerin ,

I have now tested the new implementation mp_sparse_fixes with my full dataset and it has finished without issues.

I have run the following command:

```
nextflow run aertslab/SCENICprotocol \
        -r mp_sparse_fixes \
        -with-report nextflow_report.html \
        -profile singularity \
        --loom_input full_dataset.loom \
        --loom_output full_dataset.SCENIC_out.loom \
        --TFs Mouse_TFs.txt \
        --motifs motifs-v9-nr.mgi-m0.001-o0.0.tbl \
        --db mm9-tss-centered-5kb-7species.mc9nr.feather \
        --threads 16 \
        --sparse
```

using 16 threads with 10G per thread on our HPC. The dataset consisted of 62603 cells and 17575 genes and finished in the following time:

```
executor >  local (10)
[e7/37085d] process > filter          [100%] 1 of 1 ✔
[86/f13a20] process > preprocess      [100%] 1 of 1 ✔
[cf/4da5e2] process > pca             [100%] 1 of 1 ✔
[7f/211598] process > visualize       [100%] 1 of 1 ✔
[cc/343d97] process > cluster         [100%] 1 of 1 ✔
[9b/1b9b0c] process > GRNinference    [100%] 1 of 1 ✔
[ff/f53b6e] process > cisTarget       [100%] 1 of 1 ✔
[08/68f1ef] process > AUCell          [100%] 1 of 1 ✔
[b1/b40525] process > visualizeAUC    [100%] 1 of 1 ✔
[83/84dcce] process > integrateOutput [100%] 1 of 1 ✔
Completed at: 11-Feb-2020 01:25:58
Duration    : 11h 23m 26s
CPU hours   : 11.8
Succeeded   : 10
```

Based on the nextflow workflow report, the GRN interference took the longest, as you suggested about 10h. I guess it is this slow because we are not using dask in this implementation?

Thanks for implementing this fix! Is the --multipcoressing command still needed or is this implemented by default now in the mp sparse fix?

**Comment by cflerin** [comment]
Great, glad you hear that you got everything working! I'll merge these changes into the master branch. Using `--multiprocessing` isn't required anymore (it was a testing option, now it's always on). 

But dask vs multiprocessing should take around the same amount of time anyway, and 10h sounds about right for your dataset. Thanks again for testing these branches!
