### ISSUE TITLE
nextflow pipeline error: Signatures dataframe is empty

### ISSUE THREAD

**Issue by Zifeng-L** [aertslab/SCENICprotocol#54]
Hi there! I tried the nextflow tool for running scenic. The command error happened in the following code : 
```
2022-05-17 00:43:43,002 - pyscenic.cli.pyscenic - INFO - Loading gene signatures.
  Traceback (most recent call last):
    File "/opt/venv/bin/pyscenic", line 8, in <module>
      sys.exit(main())
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 470, in main
      args.func(args)
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 220, in aucell_command
      signatures = load_signatures(args.signatures_fname.name)
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/cli/utils.py", line 175, in load_signatures
      return df2regulons(load_motifs(fname, sep=suffixes_to_separator(extension)))
    File "/opt/venv/lib/python3.7/site-packages/pyscenic/transform.py", line 308, in df2regulons
      assert not df.empty, 'Signatures dataframe is empty!
```
  AssertionError: Signatures dataframe is empty!`

I checked the config and thought it may be associated with the threshold in the config:
```
       cistarget {
            adj = 'adj.tsv'
            type = ''
            rank_threshold = 5000
            auc_threshold = 0.05
            nes_threshold = 3.0
            min_orthologous_identity = 0.0
            max_similarity_fdr = 0.001
            annotations_fname = ''
            thresholds = '0.75,0.90'
            top_n_targets = 50
            top_n_regulators = '5,10,50'
            min_genes = 20
            all_modules = false
            motifsDb = 'pyscenic/mm10/mm10__refseq-r80__*feather'
            motifsAnnotation = 'pyscenic/mm10/motifs-v9-nr.mgi-m0.001-o0.0.tbl'
         }
```
which threshold should I change? Will it result in different regulons? Can anyone help me?

**Comment by maminby** [comment]
have you solved this? I ran into the same troulble

**Comment by maminby** [comment]
I solved this, I found that my reference file shall be for mouse. Once I corrected it the error didn't come out
